Added info about Singularity image and removed SpliceAI section...
molgenis/capice pull request #142
Opened 2022-10-25 10:30 UTC by svandenhoek

… (deprecated & files on download server are already mentioned elsewhere).

## SOP

### Changed

-

## Important notes

-

### Before merge:
- [ ] Functionality works & meets specs
- [ ] No Travis issues
- [ ] Code reviewed
- [ ] Documentation was updated

### After merge:
- [ ] Added feature/fix to draft release notes
- [ ] Removed merged branches

2022-10-25 10:38 UTC, SietsmaRJ requested changes
We can't expect people to install both CAPICE from either source or PIP and also install singularity, but then not explain how you can get the SpliceAI working. I'm in favor of adding the Singularity part to the readme, but I'd like to keep the SpliceAI section too, in case someone does not want to use the molgenis download server (or if Illumina takes down the SpliceAI resources from the molgenis download server).

2022-10-25 11:10 UTC, svandenhoek commented
> but then not explain how you can get the SpliceAI working

The section that was removed contained outdated information. The requirements already contain which files & plugins are needed and download links for them:
![Schermafbeelding 2022-10-25 om 13 06 41](https://user-images.githubusercontent.com/7658246/197757844-1efda656-aec9-4e4f-abe8-52a8758496cf.png)

2022-10-25 12:05 UTC, svandenhoek commented
Added back information under separate section.

2022-10-27 07:46 UTC, SietsmaRJ approved these changes

2022-10-27 07:46 UTC, merged