Feat/json models
molgenis/capice pull request #151
Opened 2022-12-05 12:55 UTC by svandenhoek

## SOP

### Changed
- Capice now uses `.json`/`.ubj` for saving/loading models.
- Added scripts to convert to/from `.pickle.dat` (note that these are simplistic without advanced user-input validation!)
- Adjustments to CLI to be more streamlined.

## Important notes

-

### Before merge:
- [ ] Functionality works & meets specs
- [ ] No Travis issues
- [ ] Code reviewed
- [ ] Documentation was updated

### After merge:
- [ ] Added feature/fix to draft release notes
- [ ] Removed merged branches

2022-12-08 12:54 UTC, SietsmaRJ requested changes
Generally: check for unused import statements.

2022-12-08 12:54 UTC, SietsmaRJ commented on tests/capice/test_main_explain.py
> +from tests.capice.test_templates import _project_root_directory, ResourceFile, load_model
See note on `args_handler_parent.py; line 5` about import statements.

2022-12-12 08:18 UTC, svandenhoek commented on src/molgenis/capice/cli/args_handler_parent.py
>          """
Main reason for it was to remove unneeded code to improve coverage (a `pass` is still seen as code that needs coverage). I don't think we need to worry about whether the method is closed correctly (see also [this](https://stackoverflow.com/a/46146159) and [this](https://stackoverflow.com/a/45826761)).

If we'd rather use `pass` consistently, also fine by me. But hopefully the explanation above makes clear why I made this change 🙂

2022-12-12 08:50 UTC, svandenhoek commented on src/molgenis/capice/cli/args_handler_parent.py
> +from xgboost import XGBClassifier
It seemed cleaner when reading pydoc, but I guess it was a bit inconsistent with the rest of the code.

2022-12-12 09:20 UTC, svandenhoek commented on src/molgenis/capice/cli/args_handler_parent.py
> +from xgboost import XGBClassifier
Fair enough, tbh didn't really look at the import order. If we want to enforce this though, maybe we should investigate if such a thing can be enforced through linting?

**Flake8 (with `flake8-import-order`):**
```
$ flake8 src/
[...]
src/molgenis/capice/cli/args_handler_parent.py:2:1: I201 Missing newline between import groups. 'import xgboost' is identified as Third Party and 'import os' is identified as Stdlib.
src/molgenis/capice/cli/args_handler_parent.py:4:1: I100 Import statements are in the wrong order. 'from abc import ABCMeta, abstractmethod' should be before 'import xgboost' and in a different group.
src/molgenis/capice/cli/args_handler_parent.py:5:1: I201 Missing newline between import groups. 'from xgboost import XGBClassifier' is identified as Third Party and 'from abc import ABCMeta, abstractmethod' is identified as Stdlib.
src/molgenis/capice/cli/args_handler_parent.py:6:1: I100 Import statements are in the wrong order. 'from molgenis.capice import __version__' should be before 'from xgboost import XGBClassifier' and in a different group.
src/molgenis/capice/cli/args_handler_parent.py:6:1: I201 Missing newline between import groups. 'from molgenis.capice import __version__' is identified as Third Party and 'from xgboost import XGBClassifier' is identified as Third Party.
[...]
```

**Pylint:**
```
$ pylint src/
[...]
src/molgenis/capice/cli/args_handler_parent.py:4:0: C0411: standard import "from abc import ABCMeta, abstractmethod" should be placed before "import xgboost as xgb" (wrong-import-order)
[...]
```

2022-12-12 09:33 UTC, svandenhoek commented on src/molgenis/capice/cli/args_handler_parent.py
> +            return arg[arg_len-1]
Seems like it might be a bug that turned into expected behaviour: https://bugs.python.org/issue16399

2022-12-12 09:42 UTC, svandenhoek commented on src/molgenis/capice/cli/args_handler_train.py
> +            '--features',
Reason for `-e` is due to the `-f` is taken and simply taking the next available character from the word (just like the previous `-m/--impute`). I would be against using the file format itself as it's rather non-descriptive and between all the functionalities we have multiple different jsons (model & training features).

2022-12-12 09:44 UTC, svandenhoek commented on src/molgenis/capice/validators/input_validator.py
> +                          f'{", ".join(extension)}')
As part of #153, I assume?

2022-12-12 10:23 UTC, svandenhoek commented on tests/capice/cli/test_args_handler_train.py
> +from argparse import ArgumentParser
Let's see what flake8 will end up deciding.

2022-12-12 10:34 UTC, svandenhoek commented on tests/capice/cli/test_args_handler_predict.py
> +        self.model.CAPICE_version = '1.0.0-'
Changed back to `setattr()`.

2022-12-12 10:38 UTC, svandenhoek commented on tests/capice/test_main_explain.py
> +from tests.capice.test_templates import _project_root_directory, ResourceFile, load_model
Assuming point above with `unittest` as separate group, then no change needed.

2022-12-12 10:41 UTC, svandenhoek commented on tests/capice/test_templates.py
>  _project_root_directory = Path(__file__).absolute().parent.parent.parent
Line 11 & 12 depend on line 10, so that's not an option.

2022-12-12 12:12 UTC, svandenhoek commented on src/molgenis/capice/validators/input_validator.py
> +                          f'{", ".join(extension)}')
Nevermind, misunderstood. Solving conversation.

2022-12-12 12:12 UTC, svandenhoek commented on src/molgenis/capice/cli/args_handler_explain.py
>  from molgenis.capice.validators.model_validator import ModelValidator
Should be fixed now through linting. If not, we need to configure linting differently.

2022-12-12 12:13 UTC, svandenhoek commented on tests/capice/test_templates.py
>  from molgenis.capice.core.logger import Logger
Should be fixed now through linting. If not, we need to configure linting differently.

2022-12-13 10:42 UTC, SietsmaRJ approved these changes

2022-12-13 10:49 UTC, merged