Fix/train feature json
molgenis/capice pull request #153
Opened 2022-12-08 13:01 UTC by SietsmaRJ

## SOP

### Changed

- Changed the input JSON to feature the input features as supplied with the dataset, not processed features.

## Important notes

- Closes #118 , closes #139 , closes #150

### Before merge:
- [ ] Functionality works & meets specs
- [ ] No Travis issues
- [ ] Code reviewed
- [ ] Documentation was updated

### After merge:
- [ ] Added feature/fix to draft release notes
- [ ] Removed merged branches

2022-12-15 15:03 UTC, svandenhoek requested changes
Only looked at the `src/`.

2022-12-16 07:33 UTC, SietsmaRJ commented on src/molgenis/capice/utilities/categorical_processor.py
> +            dataset[feature] = np.nan
No, this is done with reason.

Within `_set_other_values()` I check with a `np.where` call to these matching derivative columns. If I have to split features coming from the model before doing this `np.where` call, we might run into issues with values that already have underscores in the value. [This](https://github.com/molgenis/capice/blob/fix/train_feature_json/tests/capice/utilities/test_categorical_processor.py#L172) test checks for that.

2022-12-16 08:30 UTC, SietsmaRJ commented on src/molgenis/capice/validators/post_vep_processing_validator.py
> +                    features_not_present.append(feature)
Twice to be precise, but agreed. 

Single for loops that add values to a list if they are (not) in another list I do not consider writing a generic function for. The time infested in figuring out how to optimally create and implement such a generic function does not outweigh duplication reduction or readability.

2022-12-21 11:07 UTC, dennishendriksen approved these changes

2022-12-21 11:08 UTC, merged