Release of CAPICE 2.0
molgenis/capice pull request #33
Opened 2021-05-03 13:31 UTC by SietsmaRJ

Refactoring++ of CAPICE is now release-able. For further details, see the individual file changes and/or commits.

2021-05-17 14:02 UTC, marikaris requested changes

2021-05-18 07:20 UTC, SietsmaRJ commented on src/main/python/core/input_checker.py
> +        # self._check_gzip_extension()
This line is commented due to the legacy version. Once CAPICE2VCF is updated to be able to process the output described in  [issue #30](https://github.com/molgenis/capice/issues/30) and [issue #31](https://github.com/molgenis/capice/issues/31), this line will become active again to reduce the stress on storage in a CAPICE output.

2021-05-18 07:21 UTC, SietsmaRJ commented on src/main/python/core/input_checker.py
> +            raise VersionError('Python3.6 must at least be installed.')
This is also indirectly stated in the setup.py. Leftover from when setup.py was not yet present. Will be removed.

2021-05-21 10:19 UTC, marikaris approved these changes

2021-05-21 10:19 UTC, merged